version: "1.0"

services:
  db:
    image: mysql
    container_name: WeShareUs-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=WeShareUs
    ports:
      - "3306:3306"
    restart: always
  front:
    build:
      context: ./WeShareUs-blog-Front
      dockerfile: ../Dockerfile.front
    ports:
      - "8080:3000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./WeShareUs-blog-Front/src:/WeShareUs-blog-Front/src
  api:
    build:
      context: ./WeShareUs-blog-API
      dockerfile: ../Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - DEV_MYSQL_HOST=db
      - DEV_MYSQL_USERNAME=root
      - DEV_MYSQL_PASSWORD=1234
      - DEV_MYSQL_PORT=3306
    depends_on:
      - db
    restart: always
    volumes:
      - ./WeShareUs-blog-API/src:/WeShareUs-blog-API/src